# Standard Dockerfile (NOT optimized)
# Image size: ~220 MB

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/DockerOptimization.dll"]
