namespace AdvancedCsharpConcepts.Advanced.ModernCSharp;

/// <summary>
/// C# 12 Primary Constructors - Silicon Valley modern coding style.
/// Eliminates boilerplate, increases readability.
/// </summary>
public class PrimaryConstructorsExample
{
    /// <summary>
    /// Traditional C# class with explicit constructor and fields.
    /// </summary>
    public class VehicleTraditional
    {
        private readonly string _brand;
        private readonly int _year;

        public VehicleTraditional(string brand, int year)
        {
            _brand = brand;
            _year = year;
        }

        public void Display() => Console.WriteLine($"{_brand} ({_year})");
    }

    /// <summary>
    /// Modern C# with record type - same functionality, less code.
    /// Best practice: Use for simple data-holding classes.
    /// Note: C# 12 primary constructors for classes require .NET 8+
    /// </summary>
    public record VehicleModern(string Brand, int Year)
    {
        public void Display() => Console.WriteLine($"{Brand} ({Year})");

        // Properties are automatically generated by record
        public string GetBrand() => Brand;
        public int GetYear() => Year;
    }

    /// <summary>
    /// Advanced: Record with validation and inheritance (C# 10+).
    /// </summary>
    public record ElectricVehicle(string Brand, int Year, int BatteryCapacityKwh)
        : VehicleModern(Brand, Year)
    {
        // Property validation
        public int BatteryCapacity { get; init; } = BatteryCapacityKwh > 0
            ? BatteryCapacityKwh
            : throw new ArgumentException("Battery capacity must be positive", nameof(BatteryCapacityKwh));

        public double Range => BatteryCapacity * 5.0; // 5 km per kWh average

        public new void Display()
        {
            base.Display();
            Console.WriteLine($"Battery: {BatteryCapacity} kWh, Range: {Range:F0} km");
        }
    }

    /// <summary>
    /// Demonstrates record types in action (C# 10+).
    /// </summary>
    public static void RunExample()
    {
        Console.WriteLine("=== C# 10/11 Record Types & Modern Features ===\n");

        // Traditional approach
        var traditionalCar = new VehicleTraditional("Tesla", 2024);
        Console.Write("Traditional class: ");
        traditionalCar.Display();

        // Modern approach with records
        var modernCar = new VehicleModern("Tesla", 2024);
        Console.Write("Modern record: ");
        modernCar.Display();

        // Advanced with inheritance
        var ev = new ElectricVehicle("Tesla Model S", 2024, 100);
        Console.Write("\nElectric Vehicle (inherited record):\n");
        ev.Display();

        Console.WriteLine($"\nBrand property: {ev.GetBrand()}");
        Console.WriteLine($"Year property: {ev.GetYear()}");

        // Record value equality
        var ev2 = new ElectricVehicle("Tesla Model S", 2024, 100);
        Console.WriteLine($"\nRecord equality: ev == ev2 → {ev == ev2}");
    }
}
