using SourceGeneratorDemo;

Console.WriteLine("=== Source Generator Demo: AutoNotifyGenerator ===\n");

// Create a PersonViewModel instance
var person = new PersonViewModel();

Console.WriteLine("Setting properties (change notifications will be triggered):\n");

// These properties are auto-generated by the Source Generator
person.FirstName = "John";
person.LastName = "Doe";
person.Age = 30;
person.Email = "john.doe@example.com";
person.IsActive = true;

Console.WriteLine($"\nCurrent state:");
Console.WriteLine($"  Full Name: {person.FullName}");
Console.WriteLine($"  Age: {person.Age}");
Console.WriteLine($"  Email: {person.Email}");
Console.WriteLine($"  Active: {person.IsActive}");

Console.WriteLine($"\nUpdating existing values (no change notifications for same values):\n");

// Setting the same value won't trigger change notification
person.FirstName = "John";  // No notification
person.Age = 30;  // No notification

Console.WriteLine($"\nUpdating with new values:\n");

person.FirstName = "Jane";  // Will trigger notification
person.Age = 25;  // Will trigger notification

Console.WriteLine($"\nFinal state:");
Console.WriteLine($"  Full Name: {person.FullName}");
Console.WriteLine($"  Age: {person.Age}");

Console.WriteLine("\n=== Demo Complete ===");
Console.WriteLine("\nKey Benefits:");
Console.WriteLine("  ✓ Zero boilerplate code for properties");
Console.WriteLine("  ✓ Automatic INotifyPropertyChanged implementation");
Console.WriteLine("  ✓ Built-in equality checking");
Console.WriteLine("  ✓ Compile-time code generation");
Console.WriteLine("  ✓ Full IntelliSense support");
